INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (1, 'MONTEVIDEO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (2, 'ARTIGAS');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (3, 'CANELONES');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (4, 'CERRO LARGO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (5, 'COLONIA');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (6, 'DURAZNO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (7, 'FLORES');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (8, 'FLORIDA');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (9, 'LAVALLEJA');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (10, 'MALDONADO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (11, 'PAYSANDU');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (12, 'RIO NEGRO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (13, 'RIVERA');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (14, 'ROCHA');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (15, 'SALTO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (16, 'SAN JOSE');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (17,'SORIANO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (18, 'TACUAREMBO');
INSERT INTO DEPARTAMENTO (ID_DEPARTAMENTO, NOMBRE) VALUES (19, 'TREINTA Y TRES');

Insert into PROYECTO.LOCALIDAD (ID_LOCALIDAD,NOMBRE,ID_DEPARTAMENTO) values ('1924','PASO DE LAS FLORES','18');

INSERT INTO PROYECTO.ESTADOS_USUARIO (ID_ESTADOS_USUARIO, NOMBRE) VALUES (1, 'SIN ACTIVAR');
INSERT INTO PROYECTO.ESTADOS_USUARIO (ID_ESTADOS_USUARIO, NOMBRE) VALUES (2, 'ACTIVO');